---
- hosts: all
  roles:
    - role: influxdb
      influxdb_overwrite_hosts_file: "yes"
    - role: telegraf
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  tasks:
    - include_tasks: tasks/main.yml
      kapacitor_influxdb_enabled: "true"
      kapacitor_tasks_to_enable:
        - name: cpu_alert
          type: stream
          tick: cpu_alert.tick
          dbrp: telegraf.default
        - name: cpu_alert_batch
          type: batch
          tick: cpu_alert_batch.tick
          dbrp: telegraf.default
        - name: disk_alert
          type: stream
          tick: disk_alert.tick
          dbrp: telegraf.default
  handlers:
    - include_tasks: handlers/main.yml
