---
- name: Copy specified TICKscript scripts to remote host
  copy:
    src: "{{ item.tick }}"
    dest: /tmp/{{ item.tick | basename }}
  with_items: "{{ kapacitor_tasks_to_enable }}"
  notify: configure_ticks
