---
- name: Create temp directory
  file:
    path: /tmp/kapacitor
    state: directory

- name: Build stream_threshold TICK
  template:
    src: stream_threshold.tick.j2
    dest: "/tmp/kapacitor/{{ item.name }}.tick"
  with_items: "{{ kapacitor_stream_thresholds }}"
  notify: configure_thresholds
  tags: build_thresholds