---
- name: Set templatized Kapacitor configuration
  template:
    src: kapacitor.conf.j2
    dest: "/etc/kapacitor/kapacitor.conf"
    force: yes
    backup: yes
    owner: kapacitor
    group: kapacitor
    mode: 0744
  notify: restart kapacitord
  when: kapacitor_template_configuration

- name: Verifying kapacitord is started
  service:
    name: kapacitor
    state: started

- include_tasks: configure-ticks.yml
  when: kapacitor_tasks_to_enable is defined
  tags: [kapacitor, ticks]

- include_tasks: configure-thresholds.yml
  when: kapacitor_stream_thresholds is defined
  tags: [kapacitor, thresholds]
