---
- name: Prepare
  hosts: all
  become: yes # for vagrant
  gather_facts: True
  tasks:
    - name: apt-proxy
      copy:
        content: "Acquire::http::Proxy \"{{ lookup('env', 'APT_PROXY') }}\"; Acquire::https::Proxy \"false\";"
        dest: /etc/apt/apt.conf.d/01proxy
      failed_when: False

    - name: Install Packages for Debian
      apt:
        update_cache: yes
        name: '{{item}}'
        state: present
      with_items:
        - apt-transport-https
        - curl
        - net-tools
      when: ansible_os_family == "Debian"

  roles:
    - name: viasite-ansible.influxdb
