---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml

driver:
  name: docker
platforms:
  - name: docker-kapacitor-centos
    image: mplachter/docker-centos7-molecule:latest
    privileged: True
    capabilities:
      - ALL
    volume:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"

  - name: docker-kapacitor-ubuntu
    image: solita/ubuntu-systemd:16.04
    privileged: True
    capabilities:
      - ALL
    volume:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"

lint:
  name: yamllint
  enabled: "true"
  options:
    c: molecule/default/yamllint_config.yml

verifier:
  name: testinfra
  directory: ../resources/tests
  options:
    verbose: True
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    links:
      group_vars:
        ../../resources/group_vars
